### ISSUE TITLE
Графический интерфейс

### ISSUE THREAD

**Issue by r4p1er** [r4p1er/EasyCipher#1]
Необходимо разработать графический интерфейс для программы шифрования файлов на базе Java Swing, основываясь на утвержденном техническом задании. Интерфейс должен быть удобным, интуитивно понятным и соответствовать следующим требованиям:

 * Возможность выбора файлов или каталогов для шифрования/дешифрования.
 * Выбор алгоритма шифрования (AES, Blowfish, Twofish).
 * Поле для ввода или генерации ключа шифрования.
 * Индикация статуса выполнения операции (ошибки, успешное выполнение).

## Шаги для выполнения

1. Изучить утвержденное ТЗ и определить требования к интерфейсу.
2. Спроектировать макет интерфейса, включая основные окна и элементы управления.
3. Реализовать графический интерфейс с использованием Java Swing.
4. Добавить обработчики пользовательского ввода (заглушки).
5. Протестировать интерфейс на предмет ошибок и удобства использования.

## Ожидаемый результат

Созданный графический интерфейс полностью соответствует требованиям ТЗ и обеспечивает:

 * Удобный выбор файлов и каталогов.
 * Настройку параметров шифрования (алгоритм, ключ).
 * Понятную индикацию выполнения операций.
 * Интуитивно понятный и отзывчивый дизайн.

**Comment by fekoneko** [comment]
Серьёзная тема

**Comment by fekoneko** [comment]
Тадададам
