### ISSUE TITLE
Локализация (ru/en)

### ISSUE THREAD

**Issue by kiespetch1** [r4p1er/EasyCipher#9]
# Локализация приложения

## Описание задачи
Цель задачи — локализовать существующее Java Swing приложение. Для этого необходимо создать класс помощник `LocalizationUtility`, который будет управлять локалями приложения, подгружать соответствующие ресурсные бандлы из указанной папки и заменять все прописанные вручную строки на получаемые через этот класс.

Необходимо обеспечить поддержку мультиязычности с использованием файлов ресурсов `.properties` для разных языков. В рамках данной задачи необходимо сделать поддержку английского и русского языков.

## Требования к реализации

1. **Класс `LocalizationUtility`**:
   - Создать класс `LocalizationUtility`, который будет управлять локалями приложения.
   - Класс должен поддерживать инициализацию локали с помощью метода `setLocale`, а также возможность получения локализованных строк через метод `getLocalizedString`.
   - Локализованные строки должны подгружаться из ресурса с использованием стандартного Java механизма `ResourceBundle`.

2. **Методы класса `LocalizationUtility`**:
   - `getLocalizedString(String key)` — метод для получения локализованной строки по ключу.
   - `setLocale(Locale locale)` — метод для смены текущей локали и перезагрузки соответствующих бандлов.

3. **Поддержка мультиязычности**:
   - Для каждого языка должен быть создан отдельный ресурсный файл, например, `MessagesBundle.properties` для английского языка и `MessagesBundle_ru.properties` для русского языка.
   - Бандлы должны содержать переводы всех строк интерфейса, которые могут отличаться в зависимости от языка.

4. **Изменение прописанных вручную строк**:
   - Все строки в коде, которые зависят от локализации, должны быть заменены на вызовы метода `LocalizationUtility.getLocalizedString()`.
   - Строки, связанные с пользовательским интерфейсом (кнопки, метки, сообщения), должны быть локализованы.

## Дополнительные замечания
- Все строки должны быть извлечены из бандлов, чтобы их было проще редактировать и добавлять переводы.

## Критерии приемки

1. Все строки интерфейса успешно заменены на вызовы метода `LocalizationUtility.getLocalizedString()`.
2. Для каждого языка добавлен соответствующий файл ресурса
3. Приложение корректно отображает текст на всех поддерживаемых языках.

## Технические детали

- Язык: Java
- Библиотеки:
  - Использовать стандартные библиотеки Java для работы с ресурсными бандлами (`ResourceBundle`, `Locale`).

**Comment by r4p1er** [comment]
Closed in #18
